# Generated by Django 5.2.2 on 2025-07-07 15:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Accommodation Name', max_length=200)),
                ('tax_id', models.CharField(default='TAXID12345678', max_length=50)),
                ('address', models.CharField(default='Accommodation Address', max_length=200)),
                ('phone', models.CharField(default='000-000-000', max_length=20)),
                ('email', models.EmailField(default='email@accommodation.com', max_length=254)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=21.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('number_of_guests', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.IntegerField()),
                ('breakdown', models.JSONField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoices.booking')),
            ],
        ),
    ]
