# Generated by Django 5.2.2 on 2025-07-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_guests',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
        migrations.AddField(
            model_name='owner',
            name='fist_name',
            field=models.CharField(default='Accommodation Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='owner',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
    ]
