# Generated by Django 5.2.2 on 2025-06-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('assassin', models.CharField(blank=True, max_length=10, null=True)),
                ('case_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
