# Generated by Django 5.2.2 on 2025-11-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscopo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signo', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('rango_fecha', models.CharField(blank=True, max_length=50)),
                ('texto', models.TextField()),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('signo', 'fecha')},
            },
        ),
    ]
