# Generated by Django 5.2.2 on 2026-01-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.JSONField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
